{% set name = "oci" %}
{% set version = "2.181.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/oci-{{ version }}.tar.gz
  sha256: 8d52a4a65bf0d20bbd59dc3248ed3747b409b5061bcf18e90f2e52f6049fd154

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - certifi
    - cryptography >=3.2.1,<50.0.0
    - pyopenssl >=17.5.0,<27.0.0
    - python-dateutil >=2.5.3,<3.0.0
    - pytz >=2016.10
    - urllib3 >=2.6.3
    - circuitbreaker >=1.3.1,<3.0.0
    - crc32c ==2.7.1

test:
  imports:
    - oci
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://docs.oracle.com/en-us/iaas/tools/python/latest/index.html
  summary: Oracle Cloud Infrastructure Python SDK
  description: |
    The Oracle Cloud Infrastructure (OCI) Python SDK enables you to write code
    to manage Oracle Cloud Infrastructure resources. It provides Python client
    libraries and API bindings for the full range of OCI services.
  license: Apache-2.0 OR UPL-1.0
  license_family: Apache
  license_file: LICENSE.txt
  doc_url: https://docs.oracle.com/en-us/iaas/tools/python/latest/index.html
  dev_url: https://github.com/oracle/oci-python-sdk

extra:
  recipe-maintainers:
    - manics
